name: Deploy Pipeline

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      namespace:
        required: true
        type: string
      project_type:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ inputs.app_name }}
      NAMESPACE: ${{ inputs.namespace }}
      PROJECT_TYPE: ${{ inputs.project_type }}

    steps:
      - uses: actions/checkout@v5

      - name: Generate Image Tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG=dev-${GITHUB_RUN_NUMBER}-${SHORT_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set Builder Image
        run: |
          if [ "$PROJECT_TYPE" = "java" ]; then
            echo "BUILDER_IMAGE=openshift/openjdk-11-rhel7" >> $GITHUB_ENV
          elif [ "$PROJECT_TYPE" = "nginx" ]; then
            echo "BUILDER_IMAGE=openshift/nginx" >> $GITHUB_ENV
          else
            echo "Unsupported project type"
            exit 1
          fi

      - name: Install oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login
        run: |
          oc login https://api.rm1.0a51.p1.openshiftapps.com:6443 \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true
          oc project $NAMESPACE

      - name: Create ImageStream
        run: oc get is $APP_NAME || oc create is $APP_NAME

      - name: Create BuildConfig
        run: |
          oc get bc $APP_NAME || oc new-build \
            --name=$APP_NAME \
            --image-stream=$BUILDER_IMAGE \
            --binary=true \
            --to=$APP_NAME:latest

      - name: Build
        run: oc start-build $APP_NAME --from-dir=. --follow

      - name: Tag Image
        run: |
          oc tag $APP_NAME:latest $APP_NAME:$IMAGE_TAG

      - name: Deploy
        run: |
          oc get deployment $APP_NAME || oc new-app $APP_NAME:latest --name=$APP_NAME

          # limit old ReplicaSets (VERY IMPORTANT)
          oc patch deployment $APP_NAME -p '{"spec":{"revisionHistoryLimit":2}}'

          # safer image update
          oc set image deployment/$APP_NAME --all-containers=$APP_NAME:$IMAGE_TAG

          oc rollout status deployment/$APP_NAME

      - name: Expose with HTTPS
        run: |
          if oc get route $APP_NAME; then
            oc patch route $APP_NAME \
              -p '{"spec":{"tls":{"termination":"edge","insecureEdgeTerminationPolicy":"Redirect"}}}'
          else
            oc expose svc $APP_NAME \
              --name=$APP_NAME \
              --port=8080 \
              --tls-termination=edge
          fi