name: Deploy Pipeline

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      namespace:
        required: true
        type: string
      project_type:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ inputs.app_name }}
      NAMESPACE: ${{ inputs.namespace }}
      PROJECT_TYPE: ${{ inputs.project_type }}

    steps:
      - uses: actions/checkout@v5

      - name: Set Builder Image
        run: |
          if [ "$PROJECT_TYPE" = "java" ]; then
            echo "BUILDER_IMAGE=java:openjdk-17-ubi8" >> $GITHUB_ENV
          elif [ "$PROJECT_TYPE" = "node" ]; then
            echo "BUILDER_IMAGE=nodejs:18-ubi8" >> $GITHUB_ENV
          else
            echo "Unsupported project type"
            exit 1
          fi

      - name: Install oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login
        run: |
          oc login https://api.rm1.0a51.p1.openshiftapps.com:6443 \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true
          oc project $NAMESPACE

      - name: Create ImageStream
        run: oc get is $APP_NAME || oc create is $APP_NAME

      - name: Create BuildConfig
        run: |
          oc get bc $APP_NAME || oc new-build \
            --name=$APP_NAME \
            --image-stream=$BUILDER_IMAGE \
            --binary=true \
            --to=$APP_NAME:latest

      - name: Build
        run: oc start-build $APP_NAME --from-dir=. --follow

      - name: Deploy
        run: |
          oc get deployment $APP_NAME || oc new-app $APP_NAME:latest --name=$APP_NAME
          oc rollout status deployment/$APP_NAME

      - name: Expose
        run: oc get route $APP_NAME || oc expose svc $APP_NAME